name: e_learning
description: An E-Learning app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  google_fonts: ^2.2.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  avatar_glow: ^2.0.2
  bouncing_widget: ^2.0.0
#  flutter_pdfview: ^1.2.1
  path: ^1.8.0
  path_provider: ^2.0.8
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.6
  syncfusion_flutter_pdfviewer: ^19.4.50-beta
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
